yangxikun/opentelemetry-lua

.github/workflows/ci.yaml
Makefile
README.md

Hi! Thanks so much for your work with this library 🙏
I use `podman-compose` instead of `docker-compose`. This PR makes that possible in this repo. It does the following:
1. Allows the user to specify a container orchestrator by passing `CONTAINER_ORCHESTRATOR` to `make` (`make openresty-dev CONTAINER_ORCHESTRATOR=podman`).
2. Defaults the value of `CONTAINER_ORCHESTRATOR` to `docker-compose` to preserve existing behavior.
3. Adds `make openresty-build` to build container images specified in `docker-compose.yml`.
4. Updates README to indicate that people should run `make openresty-build` before `make openresty-dev`.
5. Renames `DOCKER_COMPOSE_EXEC_OPTIONS` to `CONTAINER_ORCHESTRATOR_EXEC_OPTIONS`

Support other container orchestrators (like Podman)

---

.gitignore

Some contributors may use [VSCode](https://code.visualstudio.com/), which may store files in the `.vscode` directory. This PR adds it to `.gitignore` to improve developer experience.

Add .vscode directory to gitignore

---

lib/opentelemetry/util.lua

If someone has already defined `timeval` using `ffi`, then they will see this error from this library: `error loading plugin: /usr/local/lib/lua/opentelemetry/util.lua:17: attempt to redefine 'timeval'.
This PR updates the code to check for `timeval` before defining it.

Check for timeval before trying to define

---

Dockerfile
rockspec/opentelemetry-lua-master-0.rockspec

I don't know if there are any api changes between the two http libraries. Will see if tests pass/fail.
Closes #14

Use lua-resty-http instead of api7-lua-resty-http

---

lib/opentelemetry/trace/exporter/http_client.lua

This PR removes an unnecessary `keepalive` call Why is it unnecessary? `http_client` calls [httpc:request_uri](https://github.com/yangxikun/opentelemetry-lua/blob/d92bb17c8514f6f73264d461d97a04e91f2aced7/lib/opentelemetry/trace/exporter/http_client.lua#L34), which [calls `:keepalive` by default](https://github.com/ledgetech/lua-resty-http#request_uri) ([code](https://github.com/ledgetech/lua-resty-http/blob/master/lib/resty/http.lua#L946-L958)).

Remove unnecessary keepalive

---

lib/opentelemetry/util.lua

[Linux's `gettimeofday` function](https://man7.org/linux/man-pages/man2/gettimeofday.2.html) uses a `timeval` struct which reports seconds and microseconds
```c
struct timeval {
time_t      tv_sec;     /* seconds */
suseconds_t tv_usec;    /* microseconds */
};
```
This is the maximum available precision from that function.
This PR updates `ffi_gettimeofday` to return `microseconds`, then updates `_M.time_nano` to point to a function that calculates nanoseconds based on that.
I made this change because I found the code confusing, and also am working on using milliseconds in another PR.
Note: using nanoseconds makes it easier to deal with the [protos](https://github.com/open-telemetry/opentelemetry-proto/blob/main/opentelemetry/proto/trace/v1/trace.proto#L158-L164), even though the library …

Return microseconds from gettimeofday

---

lib/opentelemetry/trace/sampling/result.lua

When working on a custom sampler, it is helpful to have access to the different values of the sampling decision enum.
This PR exports the different sampling decisions' integer mapping.

allow semantic access to result enum values

---

Makefile
busted-runner
lib/opentelemetry/trace/exporter/http_client.lua
lib/opentelemetry/trace/exporter/otlp.lua
lib/opentelemetry/trace/id_generator.lua
lib/opentelemetry/util.lua
spec/trace/exporter/otlp_spec.lua

Per the [spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/exporter.md#retry), SDKs' exporters should have a retry strategy with exponential backoff and jitter.
This PR:
- Adds retries and exponential backoff to otlp exporter
- Updates `util` to include a `gettimeofday_ms()` method
- Also includes changes from a [separate PR](https://github.com/yangxikun/opentelemetry-lua/pull/21)
- Adds a `busted` test harness, which runs specs in the `resty` context (which makes `ngx` variable access possible)

Add exponential backoff for calls to collector

---

lib/opentelemetry/context.lua
lib/opentelemetry/global.lua
t/context.t

A couple follow-ups to #24:
- `ngx.ctx` was being invoked prior to `nginx.ctx` existing in openresty. We can solve this problem by wrapping the `context_storage` field in a getter.
- `context.current` was sometimes returned `nil`. I think it's nice to return an empty `context` so that users can rely on that API.

wrap context_storage in getter; fallback to empty context

---

README.md
lib/opentelemetry/global.lua
lib/opentelemetry/metrics_reporter.lua
lib/opentelemetry/trace/batch_span_processor.lua
lib/opentelemetry/trace/exporter/otlp.lua
rockspec/opentelemetry-lua-master-0.rockspec

OpenTelemetry's Ruby SDK has a `MetricsReporter` class which can be used to send metrics about the export pipeline ([original pr](https://github.com/open-telemetry/opentelemetry-ruby/pull/510)). I think it would be useful in opentelemetry-lua so I have ported over the functionality.

Add metrics reporter

---

lib/opentelemetry/trace/propagation/text_map/trace_context_propagator.lua
spec/trace/propagation/text_map/trace_context_propagator_spec.lua

Return unmodified context when traceparent header is absent

---

lib/opentelemetry/trace/propagation/text_map/trace_context_propagator.lua

Make `parse_trace_state` available outside of this module, so it can be reused more easily.

Export tracestate parse function

---

lib/opentelemetry/trace/non_recording_span.lua
lib/opentelemetry/trace/noop_span.lua
lib/opentelemetry/trace/recording_span.lua
t/trace/span_finish_timestamp.t

The spec allows users to specify the time at which their spans end: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#end. This PR adds ability to do this in the library.

Allow user to specify end timestamp when finishing span

---

lib/opentelemetry/trace/propagation/text_map/trace_context_propagator.lua
lib/opentelemetry/util.lua

These functions are generally useful, so I would like to share them in `utils`.

Move split and trim to utils

---

lib/opentelemetry/trace/propagation/text_map/trace_context_propagator.lua
lib/opentelemetry/trace/span_context.lua
spec/trace/span_context_spec.lua

Span contexts with trace id `00000000000000000000000000000000` or span id `0000000000000000` [are not valid](https://www.w3.org/TR/trace-context/#trace-id).

Check span id and trace id when checking span_context validity

---

lib/opentelemetry/context.lua
spec/context_spec.lua

I found this bug when investigating why the Baggage Propagator was not working. The propagator extraction works fine, but when we  create new spans with `with_span`, we do not copy the parent context's entries, so when we `inject`, there's nothing there. This PR

Copy current context entries in with_span

---

Makefile
README.md
benchmark/id_generator.lua
benchmark/run.sh
lib/opentelemetry/trace/exporter/console.lua
lib/opentelemetry/trace/id_generator.lua
spec/trace/id_generator_spec.lua

**Background**
Older versions of Lua, such as 5.1 (which LuaJIT, and hence OpenResty, is compatible with) has trouble with really big numbers. This is why the repo's ID generator involves concatenating strings. I don't know the full details here, so please correct me if I'm missing something.
**Benchmarks**
`5m new ids: 10.136033 seconds.`
`5m new ids: 0.118243 seconds.`
**Code Changes**
I investigated speeding ID generation up (it's a substantial portion of all CPU time), and I think that this makes it 92 times faster (woo). The existing code generates a random number between 0 and 255, which will generate a hexadecimal character between `00` and `ff`. For a span ID, it does this 8 times (resulting in a 16 character hexadecimal span ID); for a trace id, it does it 16 times (resulting in …

Speed up id generator

---

lib/opentelemetry/context.lua
lib/opentelemetry/trace/noop_span.lua
spec/context_spec.lua

Fixes https://github.com/yangxikun/opentelemetry-lua/issues/88

Use different context instance for each noop span

---

lib/opentelemetry/trace/exporter/encoder.lua

```
2024/03/13 15:50:54 [info] 4#4: *103 [lua] console.lua:32: export_spans(): Export spans:
---------------------------------------------------------
resource_attributes = {
1 = {
key = "telemetry.sdk.language"
value = {
string_value = "lua"
}
}
2 = {
key = "telemetry.sdk.name"
value = {
string_value = "opentelemetry-lua"
}
}
3 = {
key = "telemetry.sdk.version"
value = {
string_value = "0.1.1"
}
}
4 = {
key = "host.name"
value = {
string_value = "db664ee9bb41"
}
}
```
Was debugging something with resource attribute export (another PR for this incoming) but figured adding this to the console exporter was an easy addition

Add resource attrs to console export

---

lib/opentelemetry/trace/exporter/otlp.lua
spec/trace/exporter/otlp_spec.lua

* Currently if 2 tracer providers or 2 tracers are exporting, there is a first one in batch wins condition for exporting spans
* This change moves encoding the body into its own function, and adds unittests for spans from different tracers and from different trace providers to ensure resource and il parts of the otlp export are set properly

Allow multiple Inst or resource for export

---

lib/opentelemetry/trace/recording_span.lua
lib/opentelemetry/trace/tracer.lua
spec/trace/exporter/otlp_spec.lua
t/trace/span_timestamps.t

* only use for recording spans
* yangxikun/opentelemetry-lua#86

Allow user to specify start time
